# Identifying special matrices
## Instructions
In this assignment, you shall write a function that will test if a 4×4 matrix is singular, i.e. to determine if an inverse exists, before calculating it.

You shall use the method of converting a matrix to echelon form, and testing if this fails by leaving zeros that can’t be removed on the leading diagonal.

Don't worry if you've not coded before, a framework for the function has already been written.
Look through the code, and you'll be instructed where to make changes.
We'll do the first two rows, and you can use this as a guide to do the last two.

### Matrices in Python
In the *numpy* package in Python, matrices are indexed using zero for the top-most column and left-most row.
I.e., the matrix structure looks like this:
```python
A[0, 0]  A[0, 1]  A[0, 2]  A[0, 3]
A[1, 0]  A[1, 1]  A[1, 2]  A[1, 3]
A[2, 0]  A[2, 1]  A[2, 2]  A[2, 3]
A[3, 0]  A[3, 1]  A[3, 2]  A[3, 3]
```
You can access the value of each element individually using,
```python
A[n, m]
```
which will give the n'th row and m'th column (starting with zero).
You can also access a whole row at a time using,
```python
A[n]
```
Which you will see will be useful when calculating linear combinations of rows.

A final note - Python is sensitive to indentation.
All the code you should complete will be at the same level of indentation as the instruction comment.

### How to submit
Edit the code in the cell below to complete the assignment.
Once you are finished and happy with it, press the *Submit Assignment* button at the top of this notebook.

Please don't change any of the function names, as these will be checked by the grading script.

In [1]:
# GRADED FUNCTION
import numpy as np

# Our function will go through the matrix replacing each row in order turning it into echelon form.
# If at any point it fails because it can't put a 1 in the leading diagonal,
# we will return the value True, otherwise, we will return False.
# There is no need to edit this function.
def isSingular(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

# This next line defines our error flag. For when things go wrong if the matrix is singular.
# There is no need to edit this line.
class MatrixIsSingular(Exception): pass

# For Row Zero, all we require is the first element is equal to 1.
# We'll divide the row by the value of A[0, 0].
# This will get us in trouble though if A[0, 0] equals 0, so first we'll test for that,
# and if this is true, we'll add one of the lower rows to the first one before the division.
# We'll repeat the test going down each lower row until we can do the division.
# There is no need to edit this function.
def fixRowZero(A) :
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
    if A[0,0] == 0 :
        raise MatrixIsSingular()
    A[0] = A[0] / A[0,0]
    return A

# First we'll set the sub-diagonal elements to zero, i.e. A[1,0].
# Next we want the diagonal element to be equal to one.
# We'll divide the row by the value of A[1, 1].
# Again, we need to test if this is zero.
# If so, we'll add a lower row and repeat setting the sub-diagonal elements to zero.
# There is no need to edit this function.
def fixRowOne(A) :
    A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        raise MatrixIsSingular()
    A[1] = A[1] / A[1,1]
    return A

def setSubDiagonalTwo(A):
    A[2] = A[2] - A[2,0] * A[0]
    if A[2,2] == 0 :
        A[2] = A[2] + A[0]
        A[2] = A[2] - A[2,0] * A[0]
    if A[2,2] == 0 :
        A[2] = A[2] + A[1]
        A[2] = A[2] - A[2,0] * A[0]
    if A[2,2] == 0 :
        A[2] = A[2] + A[3]
        A[2] = A[2] - A[2,0] * A[0]

    A[2] = A[2] - A[2,1] * A[1]

    if A[2,2] == 0 :
        A[2] = A[2] + A[3]

        A[2] = A[2] - A[2,0] * A[0]
        if A[2,2] == 0 :
            A[2] = A[2] + A[0]
            A[2] = A[2] - A[2,0] * A[0]
        if A[2,2] == 0 :
            A[2] = A[2] + A[1]
            A[2] = A[2] - A[2,0] * A[0]
        A[2] = A[2] - A[2,1] * A[1]

    return A

# This is the first function that you should complete.
# Follow the instructions inside the function at each comment.
def fixRowTwo(A) :
    print("fixRowTwo Input\n{0}".format(A))
    # Insert code below to set the sub-diagonal elements of row two to zero (there are two of them).
    A = setSubDiagonalTwo(A)
    
    # Next we'll test that the diagonal element is not zero.
    if A[2,2] == 0 :
        # Insert code below that adds a lower row to row 2.
        if A[1,1] == 0 :
            A[1] = A[1] + A[3]

        # Now repeat your code which sets the sub-diagonal elements to zero.
        A = setSubDiagonalTwo(A)
        
    if A[2,2] == 0 :
        raise MatrixIsSingular()
        
    # Finally set the diagonal element to one by dividing the whole row by that element.
    A[2] = A[2] / A[2,2]
    
    return A

def setSubDiagonalThree():
    A[3] = A[3] - A[3,0] * A[0]
    if A[3,3] == 0 :
        A[3] = A[3] + A[0]
        A[3] = A[3] - A[3,0] * A[0]
    if A[3,3] == 0 :
        A[3] = A[3] + A[1]
        A[3] = A[3] - A[3,0] * A[0]
    if A[2,2] == 0 :
        A[3] = A[3] + A[2]
        A[3] = A[3] - A[3,0] * A[0]

    A[3] = A[3] - A[3,1] * A[1]
    A[3] = A[3] - A[3,2] * A[2]

    return A

# You should also complete this function
# Follow the instructions inside the function at each comment.
def fixRowThree(A) :
    # Insert code below to set the sub-diagonal elements of row three to zero.
    A = setSubDiagonalThree()
    
    # Complete the if statement to test if the diagonal element is zero.
    if A[3,3] == 0 :
        raise MatrixIsSingular()
        
    # Transform the row to set the diagonal element to one.
    A[3] = A[3] / A[3,3]

    return A

In [2]:
A = np.array([[ 1.       ,  7.5      , -2.5      ,  3.5      ],
       [-0.       ,  1.       , -0.7142857,  0.4285714],
       [ 1.       , -3.       ,  5.       , -2.       ],
       [ 1.       ,  3.       ,  1.       ,  3.       ]], dtype=np.float_)
fixRowTwo(A)
print("A result\n{0}".format(A))

fixRowTwo Input
[[ 1.         7.5       -2.5        3.5      ]
 [-0.         1.        -0.7142857  0.4285714]
 [ 1.        -3.         5.        -2.       ]
 [ 1.         3.         1.         3.       ]]
A result
[[  1.00000000e+00   7.50000000e+00  -2.50000000e+00   3.50000000e+00]
 [ -0.00000000e+00   1.00000000e+00  -7.14285700e-01   4.28571400e-01]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00  -6.66666867e+06]
 [  1.00000000e+00   3.00000000e+00   1.00000000e+00   3.00000000e+00]]


## Test your code before submission
To test the code you've written above, run the cell (select the cell above, then press the play button [ ▶| ] or press shift-enter).
You can then use the code below to test out your function.
You don't need to submit this cell; you can edit and run it as much as you like.

Try out your code on tricky test cases!

In [3]:
A = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_)
isSingular(A)

fixRowTwo Input
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  4.  4.]
 [ 0.  0.  5.  5.]]


False

In [4]:
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float_)
fixRowZero(A)

array([[  1. ,   7.5,  -2.5,   3.5],
       [  2. ,   8. ,   0. ,   4. ],
       [  3. ,  12. ,   0. ,   5. ],
       [  1. ,   3. ,   1. ,   3. ]])

In [5]:
fixRowOne(A)

array([[  1.        ,   7.5       ,  -2.5       ,   3.5       ],
       [ -0.        ,   1.        ,  -0.71428571,   0.42857143],
       [  3.        ,  12.        ,   0.        ,   5.        ],
       [  1.        ,   3.        ,   1.        ,   3.        ]])

In [6]:
fixRowTwo(A)

fixRowTwo Input
[[  1.           7.5         -2.5          3.5       ]
 [ -0.           1.          -0.71428571   0.42857143]
 [  3.          12.           0.           5.        ]
 [  1.           3.           1.           3.        ]]


array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [7]:
fixRowThree(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [9]:
sigma = np.tanh
W = np.array([[-2, 4, -1],[6, 0, -3]])
b = np.array([0.1, -2.5])
x = np.array([0.3, 0.4, 0.1])

In [13]:
sigma(W@x - b)

array([ 0.66403677,  0.9993293 ])

In [18]:
a1_0, a1_1 = sigma(W@x + b)

In [19]:
a1_0

0.76159415595576485

In [20]:
a1_1

-0.76159415595576496

In [1]:
def f (x) :
  return x**6/6 - 3*x**4 - 2*x**3/3 + 27*x**2/2 + 18*x - 30

def d_f (x) :
  return x**5 - 12 * x**3 - 2 * x**2 + 27*x + 18

In [4]:
x = 1

x - f(x)/d_f(x)

1.0625

In [3]:
import numpy as np

In [28]:
def f (x, y) :
    return np.exp(-(2*x*x + y*y - x*y) / 2)

def g (x, y) :
    return x*x + 3*(y+1)**2 - 1

# Next their derivatives,
def dfdx (x, y) :
    return 1/2 * (-4*x + y) * f(x, y)

def dfdy (x, y) :
    return 1/2 * (x - 2*y) * f(x, y)

def dgdx (x, y) :
    return 2 * x

def dgdy (x, y) :
    return 6 * (y + 1)

In [29]:
from scipy import optimize

def DL (xyλ) :
    [x, y, λ] = xyλ
    return np.array([
            dfdx(x, y) - λ * dgdx(x, y),
            dfdy(x, y) - λ * dgdy(x, y),
            - g(x, y)
        ])

(x0, y0, λ0) = (-1, -1, 0)
x, y, λ = optimize.root(DL, [x0, y0, λ0]).x
print("x = %g" % x)
print("y = %g" % y)
print("λ = %g" % λ)
print("f(x, y) = %g" % f(x, y))

g(x, y)

x = -0.958963
y = -1.1637
λ = -0.246538
f(x, y) = 0.353902


3.6253444690714787e-11

In [39]:
(x0, y0, λ0) = (1, -1, 0)
x, y, λ = optimize.root(DL, [x0, y0, λ0]).x
print("x = %g" % x)
print("y = %g" % y)
print("λ = %g" % λ)
print("f(x, y) = %g" % f(x, y))

g(x, y)

x = 0.930942
y = -1.21083
λ = -0.152319
f(x, y) = 0.114944


3.0775382242609339e-13

In [41]:
(x0, y0, λ0) = (0.1, -0.5, 0)
x, y, λ = optimize.root(DL, [x0, y0, λ0]).x
print("x = %g" % x)
print("y = %g" % y)
print("λ = %g" % λ)
print("f(x, y) = %g" % f(x, y))

g(x, y)

x = -0.0958377
y = -0.425307
λ = 0.101108
f(x, y) = 0.923811


7.6161299489285739e-14

In [45]:
(x0, y0, λ0) = (0.01, -2, 0)
x, y, λ = optimize.root(DL, [x0, y0, λ0]).x
print("x = %g" % x)
print("y = %g" % y)
print("λ = %g" % λ)
print("f(x, y) = %g" % f(x, y))

g(x, y)

x = -0.626142
y = -1.45017
λ = -0.156503
f(x, y) = 0.371748


-4.1213032986320286e-11

In [150]:
# Import libraries
import numpy as np
from scipy import optimize

# First we define the functions, YOU SHOULD IMPLEMENT THESE
def f (x, y) :
    return -np.exp(x - y*y + x*y)

def g (x, y) :
    return np.cosh(y) + x - 2

# Next their derivatives, YOU SHOULD IMPLEMENT THESE
def dfdx (x, y) :
    return f(x,y) * (1 + y)

def dfdy (x, y) :
    return f(x,y) * (x - 2 * y)

def dgdx (x, y) :
    return 1.0

def dgdy (x, y) :
    return np.sinh(y)

# Use the definition of DL from previously.
def DL (xyλ) :
    [x, y, λ] = xyλ
    return np.array([
            dfdx(x, y) - λ * dgdx(x, y),
            dfdy(x, y) - λ * dgdy(x, y),
            - g(x, y)
        ])

# To score on this question, the code above should set
# the variables x, y, λ, to the values which solve the
# Langrange multiplier problem.

# I.e. use the optimize.root method, as you did previously.

#x, y, λ = optimize.root(DL, [-1, -1, 0]).x
x, y, λ = (0, 0, 0)

print("x = %g" % x)
print("y = %g" % y)
print("λ = %g" % λ)
print("f(x, y) = %g" % f(x, y))

g(x, y)

x = 0
y = 0
λ = 0
f(x, y) = -1


-1.0

In [48]:
x, y, λ = optimize.root(DL, [1, 1, 0]).x


print("x = %g" % x)
print("y = %g" % y)
print("λ = %g" % λ)
print("f(x, y) = %g" % f(x, y))

g(x, y)

x = -1.33514
y = 1.87439
λ = -0.00184518
f(x, y) = -0.000641937


7.6072481647315726e-13

In [49]:
x, y, λ = optimize.root(DL, [1, -1, 0]).x


print("x = %g" % x)
print("y = %g" % y)
print("λ = %g" % λ)
print("f(x, y) = %g" % f(x, y))

g(x, y)

x = -1.6116
y = -1.95756
λ = 0.0970818
f(x, y) = -0.101385


2.4291679778798425e-13

In [57]:
x, y, λ = optimize.root(DL, [-4, 3, 0]).x


print("x = %g" % x)
print("y = %g" % y)
print("λ = %g" % λ)
print("f(x, y) = %g" % f(x, y))

g(x, y)

x = -5.32338
y = 2.67953
λ = -2.47904e-13
f(x, y) = -2.37178e-12


-1.4210854715202004e-14

In [3]:
import matplotlib
import numpy as np
import matplotlib.cm as cm
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt

matplotlib.rcParams['xtick.direction'] = 'out'
matplotlib.rcParams['ytick.direction'] = 'out'

delta = 0.025
x = np.arange(2, 3, delta)
y = np.arange(1, 2, delta)
X, Y = np.meshgrid(x, y)

Z = f(X,Y)
#Z = -np.exp(X)

# Create a simple contour plot with labels using default colors.  The
# inline argument to clabel will control whether the labels are draw
# over the line segments of the contour, removing the lines beneath
# the label
plt.figure(figsize=(15, 10))
#plt.plot(x, -np.exp(x))
CS = plt.contour(X, Y, Z, 20)
plt.clabel(CS, inline=1, fontsize=10)
plt.title('Simplest default with labels')


plt.show()

NameError: name 'f' is not defined

In [7]:
import numpy as np

def linfit(xdat, ydat):
    xbar = sum(xdat)/len(xdat)
    ybar = sum(ydat)/len(ydat)
    
    m = np.sum((xdat - xbar) * ydat) / np.sum(((xdat - xbar)**2))
    c = ybar - m * xbar
    return [m, c]

In [8]:
linfit(np.array([0.8, 0.7, 0.6, 0.5, 0.4]), np.array([0.85, 0.75, 0.55, 0.25, 0.1]))

[2.0000000000000004, -0.70000000000000007]